# UE5 build system folders
Binaries/
Build/
DerivedDataCache/
Intermediate/
Saved/
*.autosave
*.backup
*.tmp

# Ignore project files generated by Visual Studio
.vscode/
.vs/
*.VC.db
*.VC.opendb
*.suo
*.user
*.userprefs
*.sdf
*.sln
*.csproj
*.xcodeproj

# OS-specific junk
.DS_Store
Thumbs.db
.AppleDouble
.LSOverride
Icon?
._*
*~
